### ISSUE TITLE
gg_season() 

### ISSUE THREAD

**Issue by jngwj** [robjhyndman/fpp3#15]
The gg_season() with the period argument added doesn't seem to work. For example, in the fpp3 textbook, I wasn't able to get the graph output when I entered vic_elec %>% gg_season(Demand, period = "week"). The error message given was: 

Error in `ggplot2::scale_color_gradientn()`:
! `breaks` and `labels` have different lengths.

Same error pops up when i change period = "day". 

I'm using R4.4.1.

**Comment by mitchelloharawild** [comment]
Update feasts and ggplot2 packages.

**Comment by jngwj** [comment]
that was a simple fix! works fine now. thanks!

**Comment by mitchelloharawild** [comment]
No problem :smile:
