### ISSUE TITLE
sqrt() transformation on pedestrian count

### ISSUE THREAD

**Issue by Mkranj** [robjhyndman/fpp3#16]
Hi, I'm working on Chapter 12 Exercise 1 with the hourly pedestrian data, limited to a single sensor for simplicity. I'm using a decomposition model with an ETS model. 
I've tried using the sqrt() transformation so that I get positive predictions and prediction intervals.  
However, I tried comparing the results to an approach without the sqrt() transformation, and the results are much closer to actual test values. Even the CRPS measure, which takes into account prediction intervals, which go way below zero, is better for the model without the transformation.

Is this a normal occurrence? I've also thought about using the latter model and then fixing the prediction so that any prediction less than zero is set to be 0, however I don't know how if I can impose the same limitation on prediction intervals?

Here is the code I've used. Is there a step I'm applying incorrectly?
```
library(tsibble)
library(ggplot2)
library(lubridate)
library(tsibble)
library(broom) 
library(dplyr)
library(fpp3)
library(feasts)

b_ped <- pedestrian %>% 
  filter(Sensor == "Bourke Street Mall (North)") %>%
  fill_gaps(Count = 0)

autoplot(b_ped, Count)

# last three months for test set

b_ped_train <- b_ped %>%
  filter_index(~ "2016-09-30")
b_ped_test <- b_ped %>%
  filter_index("2016-10-01" ~ .)

# Train a decomposition model WITH square root transformation
b_ped_dec <- model(b_ped_train,
                   decomposition_model(
                     STL(sqrt(Count) ~ trend() +
                           season(period = "1 day") +
                           season(period = "1 week")),
                     ETS(season_adjust ~ season("N"))
                   )
)

dec_fc <- forecast(b_ped_dec,
                   h = nrow(b_ped_test))

autoplot(dec_fc) + autolayer(b_ped, Count)

# Don't use square root

b_ped_dec_nosqrt <- model(b_ped_train,
                     decomposition_model(
                       STL(Count ~ trend() + 
                             season(period = "1 day") + 
                             season(period = "1 week")),
                       ETS(season_adjust ~ season("N"))
                     )
)

dec_fc_nosqrt <- forecast(b_ped_dec_nosqrt,
                     h = nrow(b_ped_test))

autoplot(dec_fc_nosqrt) + autolayer(b_ped, Count)

# Compare RMSE and CRPS
accuracy(dec_fc, b_ped_test, list(rmse = RMSE,
                                  CRPS = CRPS))
accuracy(dec_fc_nosqrt, b_ped_test, list(rmse = RMSE,
                                    CRPS = CRPS))
```

Many thanks for the book!

**Comment by robjhyndman** [comment]
Neither model works well. The question asks for a dynamic harmonic regression model, which you should find does a little better. In future, please ask questions at https://forum.posit.co/. This is the place to report bugs in the fpp3 package.
